# Docker Composeバージョン
version: '3' 

services:
    # DB Server MySQL
    flowershopdb:
        container_name: "flower_db_mysql"
        hostname: "flower_db_server"
        image: mysql:5.7
        tty: true
        env_file:
            - ~/workspace/flowershop/docker/devenv/mysql/flower_mysql.env
        ports:
            - "59306:59306"
        volumes:
            - ~/workspace/flowershop/docker/devenv/mysql/initdb.d:/docker-entrypoint-initdb.d
            - ~/workspace/flowershop/docker/devenv/mysql/conf.d:/etc/mysql/conf.d
            - ~/workspace/flowershop/log/mysql:/var/log/mysql
        networks:
            flower_web_segment:
                ipv4_address: 172.20.0.20
        logging:
            driver: "json-file"
            options: 
                max-size: "10m" 
                max-file: "3"

# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  flower_web_segment:
    driver: bridge
    ipam:
        config:
            -
              subnet: 172.20.0.0/24
